### PR TITLE
[IS-780] - Report failed pods

### PR DESCRIPTION
**Pull request by theobarberbany**
This PR adds reporting for failed pods. It parses the aggregate error returned by the drain function.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Looks good, one quick thought I had though is that maybe we could use a regex rather than a strings split, might be safer?

**Review by JoelSpeed — COMMENTED** [review]
Added some notes as I've read through, nits mainly

**Review by JoelSpeed — COMMENTED** [review]
Somme nits, sorry

**Review by mthssdrbrg — APPROVED** [review]
If the latest changes have been tested on a cluster then :+1:

**Pull request merged**
